version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev:dc
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
