### USERS ************************************************

### Get all users
GET http://localhost:5000/api/users

### Sign Up
POST http://localhost:5000/api/signup HTTP/1.1
content-type: application/json

{
  "name": "VitaAlex",
  "email": "jban@mail.ru",
  "password": "123"
}

### Sign In
POST http://localhost:5000/api/signin HTTP/1.1
content-type: application/json

{
  "email": "jban@mail.ru",
  "password": "123"
}

### PROJECTS ************************************************

### Get all projects
GET http://localhost:5000/api/projects HTTP/1.1

### Init project
POST http://localhost:5000/api/projects HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiamJhbnRlYW1AbWFpbC5ydSIsImlhdCI6MTczNzcyODU4MywiZXhwIjoxNzM3OTAxMzgzfQ.TLpgSX8t1j9jSLLH3udcHg-poIveGO1dUg6PocQj_AA

{
  "title": "Super project2",
  "description": "super description2"
}

### Add user to project
PUT http://localhost:5000/api/projects/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiamJhbnRlYW1AbWFpbC5ydSIsImlhdCI6MTczNzcyODU4MywiZXhwIjoxNzM3OTAxMzgzfQ.TLpgSX8t1j9jSLLH3udcHg-poIveGO1dUg6PocQj_AA

{
  "addedUserId": 2
}

### TASKS ************************************************

### Add task to project
POST http://localhost:5000/api/projects/2/tasks HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiamJhbnRlYW1AbWFpbC5ydSIsImlhdCI6MTczNzcyODU4MywiZXhwIjoxNzM3OTAxMzgzfQ.TLpgSX8t1j9jSLLH3udcHg-poIveGO1dUg6PocQj_AA

{
  "title": "Super task",
  "description": "super description",
  "deadline": "2025-01-22T11:56:53.206Z"
}

### Assign task to performer
PUT http://localhost:5000/api/projects/2/tasks/2/assign HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiamJhbkBtYWlsLnJ1IiwiaWF0IjoxNzM3ODAzODkxLCJleHAiOjE3Mzc5NzY2OTF9.kjgVoIamfWMzNKKC26EmG9BPN_6SdxBVXHCs-bYXylw

{
  "performerId": 2
}

### Change status of task
PUT http://localhost:5000/api/projects/1/tasks/1/status HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiamJhbnRlYW1AbWFpbC5ydSIsImlhdCI6MTczNzcyODU4MywiZXhwIjoxNzM3OTAxMzgzfQ.TLpgSX8t1j9jSLLH3udcHg-poIveGO1dUg6PocQj_AA

{
  "status": "IN_PROGRESS"
}